# Site settings
name: qfzwy's Blog
email: qfzwysec@163.com
author: qfzwy
url: https://qfzwysec.github.io/
resume_site: 
github: https://github.com/qfzwysec/
baseurl: ""
description: 记录web攻防，移动安全，芯片安全学习心得!
meta_description: 个人博客
motto: Just do it.
banner: 你有多少决心。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qfzwysec

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

